### PR TITLE
Use automatic instance manager

### PR DESCRIPTION
**Pull request by ryantxu**
in recent sdk versions, the instance manager is handled automagically -- this is much less error prone and easier to debug

### CODE REVIEW

**Comment by ryantxu** [comment]
@sunker -- any thoughts on the e2e failure with this update?  I removed any toolkit changes :man_shrugging:

**Comment by sunker** [comment]
hmm I don't know. it's working fine locally. can also see that other data source, such as appdynamics, get the same error message in the e2e build step, but that doesn't seem to fail the entire build. See https://drone.grafana.net/grafana/appdynamics-grafana-datasource/100/1/14

@scottlepp any thoughts?

**Comment by scottlepp** [comment]
@ryantxu @sunker 

The e2e test failed:  https://console.cloud.google.com/storage/browser/_details/plugins-ci/drone/grafana/timestream-datasource/pull-requests/91/artifacts/smoke.spec.ts.mp4?authuser=0&project=grafanalabs-global

It runs against latest Grafana version and is failing for version 8 because a selector changed.  There are a few ways to override this now, but try this:

Add @grafana/e2e-selectors to your dev dependencies.  The version you use there will dictate which version of Grafana the e2e test will run against, and should use the proper selectors.

You may have to use a 7.x version as @vickyyyyyyy has some fixes for 8.x e2e.

**Comment by sunker** [comment]
Adding @grafana/e2e-selectors solved the problem. Thanks a lot @scottlepp!!

@ryantxu the PR should be ready to merge now.

**Pull request merged**
