### PR TITLE
Upgrade @grafana/ dependencies to v9.2.4

### PR DESCRIPTION
**Pull request by idastambuk**
Needed in order to use the new useDefaultQuery method from: https://github.com/grafana/cloud-data-sources/issues/79

### CODE REVIEW

**Review by kevinwcyu — APPROVED** [review]

**Review by iwysiu — APPROVED** [review]
Approved! But should we worry about the failing code coverage?

**Comment by fridgepoet** [comment]
@idastambuk code coverage repo is here https://github.com/grafana/code-coverage, not sure if you already knew.
We can have a look at that together if you want. Also I just heard about a way to run github actions locally! https://github.com/nektos/act

**Comment by idastambuk** [comment]
> Approved! But should we worry about the failing code coverage?

Had to do some changes to the code-coverage repo in order for the required dependencies to be installed and tests to run. It's now passing. There's more info here: https://github.com/grafana/code-coverage/pull/21

**Comment by idastambuk** [comment]
Deps need to be updated to 9.3.2 which contains some e2e test fixes, which will be solved with this PR: https://github.com/grafana/timestream-datasource/pull/199

**Pull request closed without merging**
