### PR TITLE
Chore: Remove circleci

### LINKED ISSUE #115: chore: migrate to Drone
We are no longer using CircleCI for most of our builds, including Grafana: https://drone.grafana.net/grafana/grafana

Migrate from CircleCi to Drone: https://drone.grafana.net/grafana/timestream-datasource/settings

### PR DESCRIPTION
**Pull request by fridgepoet**
Circleci webhook has been deleted

Closes #115

### CODE REVIEW

**Review by iwysiu — APPROVED** [review]
lgtm! (Like mentioned on slack) Maybe look into why it ran circle ci on this.

**Comment by andresmgot** [comment]
We need to stop building in CircleCI first but I am still not able to do so:
Screenshot from 2021-12-20 09-35-25

can you @vickyyyyyyy ?

**Comment by vickyyyyyyy** [comment]
> We need to stop building in CircleCI first but I am still not able to do so: Screenshot from 2021-12-20 09-35-25
> 
> can you @vickyyyyyyy ?

Nope, it looks like I don't have admin access for CircleCI either

@ryantxu is this something you can help with?

**Comment by fridgepoet** [comment]
Thanks, Ryan. 
I'm going to go ahead and try merging.

**Pull request merged**
