### PR TITLE
Correcting region from eu-west-2 to eu-west-1

### LINKED ISSUE #50: Incorrect region for europe
The region for eu should be eu-west-1 and not eu-west-2

https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-timestream-now-generally-available/#:~:text=There%20are%20no%20upfront%20costs,regions%20in%20the%20coming%20months.

### PR DESCRIPTION
**Pull request by mmedum**
Fixes #50

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]

**Comment by ryantxu** [comment]
Thanks -- you should also be able to type in any region you want

**Comment by ximsandthings** [comment]
@ryantxu Any ETA on when this would be deployed with the fix on it? Want to give this user a rough timeline. Thanks.

**Comment by ryantxu** [comment]
soon -- aiming for today, but may be tomoorow

**Comment by ximsandthings** [comment]
hi @ryantxu was this deployed yet? not sure if status would change if so. thanks!

**Pull request merged**
