### PR TITLE
Increase label width to fix overflow.

### LINKED ISSUE #215: Increase label width in query editor
**What happened**:
The label for `Wait for all queries` is overflowing.
Screen Shot 2022-12-16 at 1 47 24 PM

**What you expected to happen**:
I expect it not to overflow

**How to reproduce it (as minimally and precisely as possible)**:
Open the query editor for a timestream datasouce

### PR DESCRIPTION
**Pull request by chinu-anand**
Fixes #215

### CODE REVIEW

**Review by kevinwcyu — APPROVED** [review]
LGTM

**Review by sarahzinger — APPROVED** [review]
Thank you so much!

**Comment by idastambuk** [comment]
@chinu-anand Hello! I sadly failed submit a comment before this was merged, which [this MR](https://github.com/grafana/timestream-datasource/pull/218) implements. I'd really appreciate it if you could check it out and review :) Thanks!

**Comment by chinu-anand** [comment]
@idastambuk nice work. Maintaining consistency is indeed an art of a frontend engineer. 👏🏻

**Pull request merged**
